name: Daily BTC Model Training

on:
  schedule:
    - cron: '0 0 * * *' # 매일 UTC 0시 (한국시간 오전 9시) 실행
  workflow_dispatch: # 수동 실행 버튼 활성화

permissions:
  contents: write # 업데이트된 가중치 파일을 커밋하기 위한 권한

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run training
        run: python train.py # 최신 데이터를 가져와 학습 후 model.pth 생성

      - name: Commit and Push weights
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add weights/model.pth weights/scaler.pkl
          git commit -m "Auto-update model weights: $(date +'%Y-%m-%d')" || exit 0
          git push
