name: Deploy Streamlit App

on:
  push:
    branches: [ "main" ]  # main 브랜치에 푸시될 때 실행

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. 코드 내려받기
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. .streamlit 폴더 만들기
    - name: Create .streamlit directory
      run: mkdir -p .streamlit

    # 3. [핵심] GitHub Secret을 이용해 secrets.toml 파일 생성
    # echo 명령어를 사용해 파일 내용을 씁니다.
    - name: Create secrets.toml from GitHub Secrets
      run: |
        echo 'UPSTAGE_API_KEY = "${{ secrets.UPSTAGE_API_KEY }}"' > .streamlit/secrets.toml

    # 4. 파일이 잘 생성되었는지 확인 (보안상 내용은 출력하지 않음)
    - name: Check secrets file existence
      run: |
        if [ -f .streamlit/secrets.toml ]; then
          echo "✅ secrets.toml file created successfully."
        else
          echo "❌ Failed to create secrets.toml."
          exit 1
        fi

    # ----------------------------------------------------------------
    # 5. 이후 배포 단계 (사용하시는 환경에 맞춰 선택하세요)
    # ----------------------------------------------------------------
    
    # [예시 A] Docker 이미지를 빌드해서 Docker Hub나 AWS ECR로 보내는 경우
    # - name: Build and Push Docker Image
    #   run: |
    #     docker build -t my-streamlit-app .
    #     # (여기에 docker push 명령어 추가)

    # [예시 B] AWS Elastic Beanstalk 등으로 배포하는 경우
    # - name: Deploy to AWS
    #   # (AWS 배포 관련 액션 추가)